@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package arekkuusu.grimoireofalice.common.item.food;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;