@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package arekkuusu.grimoireofalice.common.entity;

import javax.annotation.ParametersAreNonnullByDefault;

import mcp.MethodsReturnNonnullByDefault;