@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package arekkuusu.grimoireofalice.client.effect;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;