@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package arekkuusu.grimoireofalice.common.event;

import mcp.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;