@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package arekkuusu.grimoireofalice.item.masks;

import javax.annotation.ParametersAreNonnullByDefault;

import mcp.MethodsReturnNonnullByDefault;